CREATE SCHEMA nba_stats
;

CREATE TABLE nba_stats.boxscore_advanced_team (
    game_id TEXT,
    team_id TEXT,
    team_city TEXT,
    team_name TEXT,
    team_tricode TEXT,
    off_rating FLOAT,
    def_rating FLOAT,
    net_rating FLOAT,
    ast_pct FLOAT,
    ast_to_ratio FLOAT,
    oreb_pct FLOAT,
    dreb_pct FLOAT,
    efg_pct FLOAT,
    ts_pct FLOAT,
    pace FLOAT,
    possessions FLOAT,
    PRIMARY KEY (game_id, team_id)
)
;

CREATE TABLE nba_stats.boxscore_advanced_player (
    game_id TEXT,
    team_id TEXT,
    team_city TEXT,
    team_name TEXT,
    team_tricode TEXT,
    person_id TEXT,
    first_name TEXT,
    last_name TEXT,
    position TEXT,
    minutes TEXT,
    off_rating FLOAT,
    def_rating FLOAT,
    net_rating FLOAT,
    ast_pct FLOAT,
    ast_to_ratio FLOAT,
    oreb_pct FLOAT,
    dreb_pct FLOAT,
    efg_pct FLOAT,
    ts_pct FLOAT,
    usage_pct FLOAT,
    pace FLOAT,
    possessions FLOAT,
    PRIMARY KEY (game_id, person_id)
)
;

CREATE TABLE gamelog (
    season_year TEXT,
    team_id TEXT,
    team_abbreviation TEXT,
    team_name TEXT,
    game_id TEXT,
    game_date DATE,
    matchup TEXT,
    wl TEXT,
    min FLOAT,
    fgm INTEGER,
    fga INTEGER,
    fg_pct FLOAT,
    fg3m INTEGER,
    fg3a INTEGER,
    fg3_pct FLOAT,
    ftm INTEGER,
    fta INTEGER,
    ft_pct FLOAT,
    oreb INTEGER,
    dreb INTEGER,
    reb INTEGER,
    ast INTEGER,
    tov FLOAT,
    stl INTEGER,
    blk INTEGER,
    blka INTEGER,
    pf INTEGER,
    pfd INTEGER,
    pts INTEGER,
    plus_minus FLOAT,
    gp_rank INTEGER,
    w_rank INTEGER,
    l_rank INTEGER,
    w_pct_rank INTEGER,
    min_rank INTEGER,
    fgm_rank INTEGER,
    fga_rank INTEGER,
    fg_pct_rank INTEGER,
    fg3m_rank INTEGER,
    fg3a_rank INTEGER,
    fg3_pct_rank INTEGER,
    ftm_rank INTEGER,
    fta_rank INTEGER,
    ft_pct_rank INTEGER,
    oreb_rank INTEGER,
    dreb_rank INTEGER,
    reb_rank INTEGER,
    ast_rank INTEGER,
    tov_rank INTEGER,
    stl_rank INTEGER,
    blk_rank INTEGER,
    blka_rank INTEGER,
    pf_rank INTEGER,
    pfd_rank INTEGER,
    pts_rank INTEGER,
    plus_minus_rank INTEGER,
    PRIMARY KEY (team_id, game_id)
);
